const COFFEE_LIST = [
  {
    id: 1,
    name: "Espresso",
    imageUrl: "/images/espresso.png",
    price: 80.0,
  },
  {
    id: 2,
    name: "Cappuccino",
    imageUrl: "/images/Cappuccino.png",
    price: 120.0,
  },
  {
    id: 3,
    name: "Latte",
    imageUrl: "/images/Latte.png",
    price: 140.0,
  },
  {
    id: 4,
    name: "Americano",
    imageUrl: "/images/Americano.png",
    price: 100.0,
  },
  {
    id: 5,
    name: "Mocha",
    imageUrl: "/images/Mocha.png",
    price: 160.0,
  },
  {
    id: 6,
    name: "Macchiato",
    imageUrl: "/images/Macchiato.png",
    price: 150.0,
  },
  {
    id: 7,
    name: "Flat White",
    imageUrl: "/images/FlatWhite.png",
    price: 130.0,
  },
  {
    id: 8,
    name: "Irish Coffee",
    imageUrl: "/images/IrishCoffee.png",
    price: 200.0,
  },
  {
    id: 9,
    name: "Affogato",
    imageUrl: "/images/Affogato.png",
    price: 170.0,
  },
  {
    id: 10,
    name: "Café au Lait",
    imageUrl: "/images/Café au Lait.png",
    price: 110.0,
  },
  {
    id: 11,
    name: "Cold Brew",
    imageUrl: "/images/ColdBrew.png",
    price: 140.0,
  },
  {
    id: 12,
    name: "Frappuccino",
    imageUrl: "/images/Frappuccino.png",
    price: 180.0,
  },
  {
    id: 13,
    name: "Turkish Coffee",
    imageUrl: "/images/Turkish Coffee.png",
    price: 130.0,
  },
  {
    id: 14,
    name: "Cortado",
    imageUrl: "/images/Cortado.png",
    price: 100.0,
  },
  {
    id: 15,
    name: "Ristretto",
    imageUrl: "/images/Ristretto.png",
    price: 90.0,
  },
  {
    id: 16,
    name: "Vienna Coffee",
    imageUrl: "/images/Vienna Coffee.png",
    price: 170.0,
  },
  {
    id: 17,
    name: "Drip Coffee",
    imageUrl: "/images/DripCoffee.png",
    price: 70.0,
  },
  {
    id: 18,
    name: "Doppio",
    imageUrl: "/images/Doppio.png",
    price: 80.0,
  },
  {
    id: 19,
    name: "Lungo",
    imageUrl: "/images/Lungo.png",
    price: 110.0,
  },
  {
    id: 20,
    name: "Red Eye",
    imageUrl: "/images/RedEye.png",
    price: 130.0,
  },
  {
    id: 21,
    name: "Mazagran",
    imageUrl: "/images/Mazagran.png",
    price: 150.0,
  },
  {
    id: 22,
    name: "Café Bombón",
    imageUrl: "/images/Café Bombón.png",
    price: 180.0,
  },
  {
    id: 23,
    name: "Café Cubano",
    imageUrl: "/images/Café Zorro.png",
    price: 120.0,
  },
  {
    id: 24,
    name: "Café Zorro",
    imageUrl: "/images/Café.png",
    price: 150.0,
  },
];

export default COFFEE_LIST;
